export const PersonalDetailsState = {
  first_name: "",
  last_name: "",
  dob: "",
  phone_number: "",
  email_id: "",
  address_type: "",
  address_line_1: "",
  address_line_2: "",
  country: "IN",
  state: null,
  city: null,
  zipcode: "",
  linkedin: "",
  github: "",
};
