# fly.toml file generated for miru-staging on 2022-09-15T16:41:09+05:30

app = "miru-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.11"
    NODE_VERSION = "16.4.2"
    RUBY_VERSION = "3.1.2"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bin/rails fly:server"
  APP_BASE_URL = "https://miru-staging.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "4s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[processes]
  web = "bundle exec puma -C config/puma.rb"
  worker = "bundle exec sidekiq -e production -C config/sidekiq.yml"
