
env:
  RAILS_ENV: test
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
  DATABASE_URL: postgres://postgres:postgres@localhost:5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres


steps:
  - label: ":run_specs:"
    commands:
      - "scripts/ci/eslint.sh"
      - "scripts/ci/rubocop.sh"
      - "scripts/ci/rspec.sh"
    plugins:
      - docker-compose#v4.9.0:
          run: app
          config: docker-compose.test.yml
    agents: stack=buildkite-aws
