development:
  adapter: solid_cable
  polling_interval: 1.second
  keep_messages_around_for: 1.day
  silence_polling: true

test:
  adapter: test

production:
  adapter: solid_cable
  polling_interval: 1.second
  keep_messages_around_for: 1.day
  channel_prefix: miru_web_production
