base_locale: en
locales:
  - en
  - en-GB
  - en-US
  - hi
  - mr
  - bn
  - gu
  - kn
  - ml
  - pa
  - ta
  - te
  - ur
  - es
  - fr
  - de
  - it
  - nl
  - id
  - pt-BR
  - tr
  - ar
  - ja
  - ko
  - zh-CN

data:
  read:
    - config/locales/%{locale}.yml
    - config/locales/*.%{locale}.yml
  write:
    - config/locales/%{locale}.yml

search:
  paths:
    - app/
    - config/
  exclude:
    - app/assets
    - app/javascript/src/i18n/index.ts
