name: RSpec Test Coverage
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 3.0.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Build and test with Rake
        run: |
          gem install bundler -v '2.2.32'
          bundle install --jobs 4 --retry 3
          COVERAGE=true bundle exec rspec
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
